services:
  - docker
addons:
  ssh_known_hosts: helper.gtmdcm.com
language: node_js
jobs:
  include:
    - stage: build
      language: node_js
      node_js: node
      install:
        - yarn global add typescript tsc
        - yarn
      script:
        - set -e
        - yarn build
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker build . pdf-generator
        - docker tag pdf-generator $DOCKER_USERNAME/pdf-generator
        - docker push $DOCKER_USERNAME/pdf-generator
